name: Run Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_URL: https://github.com/Davrpob0/topicosAvanzados-Test.git
  WORKING_DIR: ./topicosAvanzados-Test

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flask app repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Flask app dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Flask app
        run: |
          source venv/bin/activate
          flask initdb
          flask translate compile
          nohup flask run > flask.log 2>&1 &

      - name: Checkout Test Repository
        run: git clone https://github.com/Davrpob0/topicosAvanzados-Test.git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.9"

      - name: Install dependencies
        run: |
          cd topicosAvanzados-Test
          npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd topicosAvanzados-Test
          npx playwright test todolist.spec.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: topicosAvanzados-Test
          path: topicosAvanzados-Test/playwright-report/
          retention-days: 30
